### ISSUE TITLE
Cython module as an installation dependency

### ISSUE THREAD

**Issue by vadi2** [MLBazaar/Cardea#93]
* Cardea version:
* Python version: 3.8
* Operating System: Ubuntu 20.04 LTS

### Description

Trying to install Cardea is failing: https://paste.ubuntu.com/p/V66PTrBGgz/

Not a python expert, but it looks like `pip3 install cython` beforehand solved the issue as it installed afterwards: https://paste.ubuntu.com/p/JsyfZ6m3J9/

**Comment by sarahmish** [comment]
Hi @vadi2, I believe that this issue is caused by `numpy` mainly then `scikit-learn` installations. Since there was an issue with `numpy` during installation in #94, I think it should fix it.

Let me know if this issue still persists!
